### ISSUE TITLE
反序列化错误

### ISSUE THREAD

**Issue by liujunfan** [JasonXuDeveloper/Nino#108]
![Uploading [24KY~A47V_O6}X1()W`(]M.png…]()

**Comment by liujunfan** [comment]
![U(67% )P8CU@CTID5M8U5HG](https://github.com/JasonXuDeveloper/Nino/assets/12061841/040aae80-cb0c-4504-8659-c3d42cd30e18)

**Comment by liujunfan** [comment]
![Uploading [24KY~A47V_O6}X1()W`(]M.png…]()

**Comment by JasonXuDeveloper** [comment]
啥信息都没提供光截个这图我咋知道你遇到啥问题。

**Comment by liujunfan** [comment]
![24KY~A47V_O6}X1()W`( M](https://github.com/JasonXuDeveloper/Nino/assets/12061841/2e19a45a-3658-487e-bc7d-6608045971cd)

**Comment by JasonXuDeveloper** [comment]
Vector2Int 也截图啊

**Comment by JasonXuDeveloper** [comment]
别用改造过的代码，用原代码先试试

**Comment by liujunfan** [comment]
Vector2也报错。试过了
Vector2Int 是unity自带的

**Comment by liujunfan** [comment]
![7GT}UR5OZLO({B03%BBJLDX](https://github.com/JasonXuDeveloper/Nino/assets/12061841/3c56e499-4529-455c-993a-ed25645b4064)
int 没问题， unity 结构报错

**Comment by JasonXuDeveloper** [comment]
别发截图了，请直接把代码粘过来

**Comment by JasonXuDeveloper** [comment]
写个能复现的案例

**Comment by liujunfan** [comment]
using Vector3 = System.Numerics.Vector3;

[NinoSerialize]
public partial class TestB
{
    public Dictionary<int, TestC> TestCs;
}

[NinoSerialize]
public partial class TestC
{
    public Vector3 v2;
    public Vector3[] v2s;
}
public class Test : MonoBehaviour
{
    public void Awake()
    {
        TestB testB = new TestB();
        testB.TestCs = new();
        TestC c1 = new TestC();
        c1.v2 = new Vector3( 10,0, 10);
        c1.v2s = new []
        {
            new Vector3( 10,0, 10),
            new Vector3( 11,0, 11)
        };
        
        testB.TestCs.Add(0, c1);

        var bytes =  Serializer.Serialize(testB);

        TestB b = Deserializer.Deserialize<TestB>(bytes);
    }
}

**Comment by liujunfan** [comment]
using Vector3 = System.Numerics.Vector3;
[NinoSerialize]
public partial class TestC
{
    public Vector3[] v2s;
}
public class Test : MonoBehaviour
{
    public void Awake()
    {
        TestC c1 = new TestC();
        c1.v2s = new []
        {
            new Vector3( 10,0, 10),
            new Vector3( 11,0, 11)
        };
        
        var bytes =  Serializer.Serialize(c1);

        TestC b = Deserializer.Deserialize<TestC>(bytes);
        int n = 0;
    }
}

**Comment by JasonXuDeveloper** [comment]
已在v2.0.0修复
