### ISSUE TITLE
如果需要多个asmdef使用，就把导入的Nino目录复制到多个带有不同asmdef的目录内

### ISSUE THREAD

**Issue by yingnierxiao** [JasonXuDeveloper/Nino#130]
多个asmdef里面使用一定要复制多个吗？？这个感觉比较难受一点

**Comment by JasonXuDeveloper** [comment]
不一定，你可以试试看其他asmdef引用同一个nino的asmdef，我之前用unity 2022.3.24会出错，新版可能修复了
