### ISSUE TITLE
在Unity中开启ILRuntime之后，反序列化数据时，Enum转换出错

### ISSUE THREAD

**Issue by JansonC** [JasonXuDeveloper/Nino#16]
问题描述：
在Unity中开启ILRuntime之后，不生成代码，反序列化数据时，Enum转换出错，Enum的数据源格式是UInt64。
假如生成代码，则不存在该问题。

测试代码：
![QQ截图20220801115806](https://user-images.githubusercontent.com/33064270/182069635-9a3cebc3-3958-4d81-b583-d419484c5aa6.png)

错误信息：
![QQ截图20220801115845](https://user-images.githubusercontent.com/33064270/182069660-2824dc5b-951e-45c4-8ca2-03d0e876eb5d.png)

**Comment by JansonC** [comment]
错误信息补充，截图看的有点费劲
ArgumentException: Object of type 'System.UInt64' cannot be converted to type 'Nino.Test.Editor.Serialization.TestEnum12'.
System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MonoField.SetValue (System.Object obj, System.Object val, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.FieldInfo.SetValue (System.Object obj, System.Object value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Nino.Serialization.Deserializer.SetMember (System.Reflection.MemberInfo info, System.Object instance, System.Object val) (at Assets/Nino/Serialization/Deserializer.cs:329)
Nino.Serialization.Deserializer.<Deserialize>g__Read|4_0 (Nino.Serialization.Deserializer+<>c__DisplayClass4_0& ) (at Assets/Nino/Serialization/Deserializer.cs:302)
Nino.Serialization.Deserializer.Deserialize (System.Type type, System.Object val, System.Byte[] data, System.Text.Encoding encoding, Nino.Serialization.Reader reader, System.Boolean returnDispose, System.Boolean skipBasicCheck, System.Boolean skipCodeGenCheck, System.Boolean skipGenericCheck, System.Boolean skipEnumCheck) (at Assets/Nino/Serialization/Deserializer.cs:309)
Nino.Serialization.Deserializer.Deserialize[T] (System.Byte[] data, System.Text.Encoding encoding) (at Assets/Nino/Serialization/Deserializer.cs:85)
Nino.Test.Editor.Serialization.Test12.Main () (at Assets/Nino/Test/Editor/Serialization/Test12.cs:14)

**Comment by JasonXuDeveloper** [comment]
TestClass和TestEnum12在热更工程还是主工程

**Comment by JansonC** [comment]
测试1：
在主工程Editor下序列化，接着反序列化出错

测试2：
在主工程Editor下序列化生成配置数据给热更工程用，热更工程反序列化出错

**Comment by JasonXuDeveloper** [comment]
测试1的 类型代码（还有Enum）在哪定义的，热更工程还是主工程。。。

**Comment by JasonXuDeveloper** [comment]
应该解决了
