### ISSUE TITLE
序列化结果的二进制数组，怎么保存读取比较快速？

### ISSUE THREAD

**Issue by YamChark** [JasonXuDeveloper/Nino#26]
序列化结果的二进制数组，怎么保存读取比较快速？

**Comment by JasonXuDeveloper** [comment]
保存為文件，比如通過System.IO內的File的WriteAllBytes和ReadAllBytes實現讀寫

**Comment by YamChark** [comment]
> 保存為文件，比如通過 System.IO 內的File的WriteAllBytes和ReadAllBytes實現讀寫

好的
