### ISSUE TITLE
疑似有内存泄漏

### ISSUE THREAD

**Issue by paris-bupt** [JasonXuDeveloper/Nino#96]
![image](https://github.com/JasonXuDeveloper/Nino/assets/5100411/c3931c3a-20fb-4f2c-a73d-70ed5dcfad00)

这里计算是否要扩容可能需要修改为：`index <= TotalLength`

否则如果不断调用隐式转换，TotalLength会不断增加：

![image](https://github.com/JasonXuDeveloper/Nino/assets/5100411/35d03755-cab4-430f-85d6-4839cbaf50be)

**Comment by JasonXuDeveloper** [comment]
index是索引，是下标，所以是一直需要小于当前长度的。
下标所允许的最大值应该是总长度-1，所以这里用小于，而非小于等于是正确的

**Comment by paris-bupt** [comment]
![image](https://github.com/JasonXuDeveloper/Nino/assets/5100411/3a9463cb-575a-4a6d-bf6f-cb2b3119fdd2)

![image](https://github.com/JasonXuDeveloper/Nino/assets/5100411/010832a3-2a01-4d11-abca-c64621a5af13)

**Comment by paris-bupt** [comment]
直觉上，EnsureCapacity函数参数的语义应该以“容量”而不是“索引”来处理会好一些

**Comment by JasonXuDeveloper** [comment]
嗯，主要是一般都是检查访问的index是否存在，所以检查的时候就是检查index是否小于totalLength了，隐式转换的地方我晚点用电脑处理一下

**Comment by JasonXuDeveloper** [comment]
应该是隐式转换的地方传入了长度去检查，实际上应该是长度-1来作为索引，这块我晚点整理一下。

**Comment by JasonXuDeveloper** [comment]
处理好了，特意增加了个用来以总量进行判断的函数
