### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by RicoTen** [JasonXuDeveloper/Nino#98]
UncheckedList的作用是什么?

**Comment by JasonXuDeveloper** [comment]
作用是索引器（indexer）内的getter和setter不会进行检查，可以参考List源码，会有一个产生一定耗时的边界检查，在大量对List的某个索引元素进行读取和写入时会有不小的额外耗时

**Comment by RicoTen** [comment]
> 作用是索引器（indexer）内的getter和setter不会进行检查，可以参考List源码，会有一个产生一定耗时的边界检查，在大量对List的某个索引元素进行读取和写入时会有不小的额外耗时

Got it 已经在项目中用上了
